

INSERT INTO users (username, password, firstname, lastname) VALUES ('Goran', 'SOdlcU', 'Göran', 'Häggstund');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Bodil', 'SOdlcU', 'Bodil', 'Stenmalm');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Ellie', 'SOdlcU', 'Ellie', 'Kristall');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Kevin', 'SOdlcU', 'Kevin', 'Coster');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Julia', 'SOdlcU', 'Julia', 'Robertsson');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Alice', 'SOdlcU', 'Alice', 'Tegner');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Peter', 'SOdlcU', 'Peter', 'Stormare');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Agnes', 'SOdlcU', 'Agnes', 'Johansson');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Simon', 'SOdlcU', 'Simon', 'Kananaios');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Viggo', 'SOdlcU', 'Viggo', 'Mårtensson');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Nancy', 'SOdlcU', 'Nancy', 'Bertram');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Lukas', 'SOdlcU', 'Lukas', 'Hingstholm');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Adele', 'SOdlcU', 'Adele', 'Brittan');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Kajsa', 'SOdlcU', 'Kajsa', 'Mendelssohn');
INSERT INTO users (username, password, firstname, lastname) VALUES ('Naima', 'SOdlcU', 'Naima', 'Nadir');
#	
INSERT INTO projects SET name='Ombygget', closed=0;
INSERT INTO projects SET name='Nybygget', closed=0;
INSERT INTO projects SET name='Startbygget', closed=0;
INSERT INTO projects SET name='Slutbygget', closed=0;
INSERT INTO projects SET name='Toppenbygget', closed=0;
INSERT INTO projects SET name='Bottenbygget', closed=0;
INSERT INTO projects SET name='Rivningsbygget', closed=0;
INSERT INTO projects SET name='Kommunalbygget', closed=0;
INSERT INTO projects SET name='Privatbygget', closed=0;
INSERT INTO projects SET name='Lyxbygget', closed=0;
#
INSERT INTO members SET username='Goran', project=1, role='manager';
INSERT INTO members SET username='Goran', project=2, role='manager';
INSERT INTO members SET username='Goran', project=3, role='manager';
INSERT INTO members SET username='Goran', project=4, role='developer';
INSERT INTO members SET username='Goran', project=5, role='architect';
INSERT INTO members SET username='Bodil', project=1, role='developer';
INSERT INTO members SET username='Bodil', project=2, role='developer';
INSERT INTO members SET username='Bodil', project=3, role='tester';
INSERT INTO members SET username='Bodil', project=4, role='tester';
INSERT INTO members SET username='Bodil', project=5, role='architect';
INSERT INTO members SET username='Ellie', project=1, role='manager';
INSERT INTO members SET username='Ellie', project=2, role='developer';
INSERT INTO members SET username='Ellie', project=3, role='tester';
INSERT INTO members SET username='Ellie', project=4, role='tester';
INSERT INTO members SET username='Ellie', project=5, role='tester';
INSERT INTO members SET username='Julia', project=1, role='architect';
INSERT INTO members SET username='Julia', project=2, role='architect';
INSERT INTO members SET username='Julia', project=3, role='architect';
INSERT INTO members SET username='Julia', project=4, role='tester';
INSERT INTO members SET username='Julia', project=5, role='developer';
INSERT INTO members SET username='Alice', project=2, role='tester';
INSERT INTO members SET username='Alice', project=4, role='developer';
INSERT INTO members SET username='Alice', project=6, role='architect';
INSERT INTO members SET username='Alice', project=8, role='tester';
INSERT INTO members SET username='Alice', project=10, role='tester';
INSERT INTO members SET username='Peter', project=6, role='manager';
INSERT INTO members SET username='Peter', project=7, role='tester';
INSERT INTO members SET username='Peter', project=8, role='tester';
INSERT INTO members SET username='Peter', project=9, role='tester';
INSERT INTO members SET username='Peter', project=10, role='tester';
INSERT INTO members SET username='Agnes', project=3, role='developer';
INSERT INTO members SET username='Agnes', project=7, role='tester';
INSERT INTO members SET username='Simon', project=4, role='developer';
INSERT INTO members SET username='Simon', project=5, role='developer';
INSERT INTO members SET username='Simon', project=6, role='developer';
INSERT INTO members SET username='Simon', project=7, role='developer';
INSERT INTO members SET username='Viggo', project=3, role='tester';
INSERT INTO members SET username='Viggo', project=4, role='architect';
INSERT INTO members SET username='Viggo', project=8, role='tester';
INSERT INTO members SET username='Viggo', project=9, role='architect';
INSERT INTO members SET username='Nancy', project=6, role='architect';
INSERT INTO members SET username='Nancy', project=7, role='developer';
INSERT INTO members SET username='Nancy', project=9, role='tester';
INSERT INTO members SET username='Nancy', project=10, role='tester';
INSERT INTO members SET username='Lukas', project=7, role='developer';
INSERT INTO members SET username='Lukas', project=10, role='tester';
INSERT INTO members SET username='Adele', project=7, role='manager';
INSERT INTO members SET username='Adele', project=8, role='manager';
INSERT INTO members SET username='Kajsa', project=1, role='tester';
INSERT INTO members SET username='Kajsa', project=2, role='tester';
INSERT INTO members SET username='Kajsa', project=3, role='developer';
INSERT INTO members SET username='Kajsa', project=4, role='tester';
INSERT INTO members SET username='Kajsa', project=5, role='architect';
INSERT INTO members SET username='Kajsa', project=6, role='tester';
INSERT INTO members SET username='Kajsa', project=7, role='architect';
INSERT INTO members SET username='Kajsa', project=8, role='architect';
INSERT INTO members SET username='Kajsa', project=9, role='architect';
INSERT INTO members SET username='Kajsa', project=10, role='architect';
INSERT INTO members SET username='Naima', project=8, role='manager';
INSERT INTO members SET username='Naima', project=9, role='manager';
INSERT INTO members SET username='Naima', project=10, role='manager';
#
INSERT INTO timeReports SET user='Goran', project=1, role='manager', activityType='11', date='2014-09-01', duration='150';
INSERT INTO timeReports SET user='Goran', project=2, role='manager', activityType='13', date='2014-09-02', duration='180';
INSERT INTO timeReports SET user='Goran', project=3, role='manager', activityType='15', date='2014-09-03', duration='200';
INSERT INTO timeReports SET user='Goran', project=4, role='developer', activityType='12', date='2014-09-03', duration='120';
INSERT INTO timeReports SET user='Goran', project=2, role='manager', activityType='16', date='2014-09-08', duration='160';
INSERT INTO timeReports SET user='Goran', project=3, role='manager', activityType='14', date='2014-09-12', duration='190';
INSERT INTO timeReports SET user='Goran', project=4, role='developer', activityType='18', date='2014-10-01', duration='190';
INSERT INTO timeReports SET user='Goran', project=2, role='manager', activityType='13', date='2014-10-03', duration='230';
INSERT INTO timeReports SET user='Goran', project=3, role='manager', activityType='21', date='2014-10-08', duration='430';
INSERT INTO timeReports SET user='Goran', project=4, role='developer', activityType='23', date='2014-10-21', duration='510';
INSERT INTO timeReports SET user='Bodil', project=1, role='developer', activityType='12', date='2014-09-16', duration='230';
INSERT INTO timeReports SET user='Bodil', project=2, role='developer', activityType='14', date='2014-09-03', duration='430';
INSERT INTO timeReports SET user='Bodil', project=3, role='tester', activityType='17', date='2014-09-02', duration='210';
INSERT INTO timeReports SET user='Bodil', project=4, role='tester', activityType='11', date='2014-09-28', duration='270';
INSERT INTO timeReports SET user='Bodil', project=5, role='architect', activityType='22', date='2014-10-07', duration='490';
INSERT INTO timeReports SET user='Bodil', project=1, role='developer', activityType='15', date='2014-10-02', duration='230';
INSERT INTO timeReports SET user='Bodil', project=3, role='tester', activityType='13', date='2014-10-03', duration='230';
INSERT INTO timeReports SET user='Bodil', project=4, role='tester', activityType='14', date='2014-10-06', duration='100';
INSERT INTO timeReports SET user='Bodil', project=1, role='developer', activityType='11', date='2014-10-09', duration='80';
INSERT INTO timeReports SET user='Bodil', project=2, role='developer', activityType='12', date='2014-10-17', duration='120';
INSERT INTO timeReports SET user='Bodil', project=3, role='tester', activityType='19', date='2014-10-21', duration='170';
INSERT INTO timeReports SET user='Bodil', project=5, role='architect', activityType='12', date='2014-10-28', duration='280';
INSERT INTO timeReports SET user='Ellie', project=1, role='manager', activityType='17', date='2014-10-23', duration='400';
INSERT INTO timeReports SET user='Ellie', project=2, role='developer', activityType='19', date='2014-10-01', duration='230';
INSERT INTO timeReports SET user='Ellie', project=4, role='tester', activityType='17', date='2014-10-02', duration='400';
INSERT INTO timeReports SET user='Ellie', project=5, role='tester', activityType='13', date='2014-09-01', duration='200';
INSERT INTO timeReports SET user='Ellie', project=1, role='manager', activityType='18', date='2014-09-02', duration='250';
INSERT INTO timeReports SET user='Ellie', project=2, role='developer', activityType='19', date='2014-09-03', duration='300';
INSERT INTO timeReports SET user='Ellie', project=3, role='tester', activityType='17', date='2014-09-07', duration='400';
INSERT INTO timeReports SET user='Ellie', project=4, role='tester', activityType='15', date='2014-10-12', duration='300';
INSERT INTO timeReports SET user='Ellie', project=1, role='manager', activityType='16', date='2014-10-25', duration='450';
INSERT INTO timeReports SET user='Ellie', project=4, role='tester', activityType='14', date='2014-10-29', duration='500';
INSERT INTO timeReports SET user='Julia', project=1, role='architect', activityType='12', date='2014-09-20', duration='300';
INSERT INTO timeReports SET user='Julia', project=2, role='architect', activityType='18', date='2014-09-19', duration='500';
INSERT INTO timeReports SET user='Julia', project=3, role='architect', activityType='19', date='2014-10-08', duration='600';
INSERT INTO timeReports SET user='Julia', project=2, role='architect', activityType='11', date='2014-10-11', duration='450';
INSERT INTO timeReports SET user='Julia', project=3, role='architect', activityType='19', date='2014-10-25', duration='610';
INSERT INTO timeReports SET user='Julia', project=2, role='architect', activityType='22', date='2014-10-28', duration='120';
INSERT INTO timeReports SET user='Julia', project=3, role='architect', activityType='22', date='2014-10-29', duration='240';
INSERT INTO timeReports SET user='Julia', project=4, role='tester', activityType='23', date='2014-10-30', duration='400';
INSERT INTO timeReports SET user='Viggo', project=4, role='architect', activityType='19', date='2014-10-01', duration='300';
INSERT INTO timeReports SET user='Viggo', project=8, role='tester', activityType='21', date='2014-10-15', duration='400';
INSERT INTO timeReports SET user='Viggo', project=9, role='architect', activityType='13', date='2014-10-13', duration='300';
INSERT INTO timeReports SET user='Viggo', project=8, role='tester', activityType='12', date='2014-10-12', duration='400';
INSERT INTO timeReports SET user='Viggo', project=9, role='architect', activityType='11', date='2014-10-21', duration='300';
INSERT INTO timeReports SET user='Kajsa', project=5, role='architect', activityType='13', date='2014-10-01', duration='200';
INSERT INTO timeReports SET user='Kajsa', project=6, role='tester', activityType='14', date='2014-10-03', duration='400';
INSERT INTO timeReports SET user='Kajsa', project=7, role='architect', activityType='15', date='2014-10-05', duration='600';
INSERT INTO timeReports SET user='Kajsa', project=8, role='architect', activityType='13', date='2014-10-08', duration='800';
INSERT INTO timeReports SET user='Kajsa', project=9, role='architect', activityType='14', date='2014-10-21', duration='100';
INSERT INTO timeReports SET user='Kajsa', project=10, role='architect', activityType='19', date='2014-10-24', duration='150';
INSERT INTO timeReports SET user='Naima', project=8, role='manager', activityType='13', date='2013-01-20', duration='150';
INSERT INTO timeReports SET user='Naima', project=9, role='manager', activityType='14', date='2013-01-25', duration='180';
INSERT INTO timeReports SET user='Naima', project=10, role='manager', activityType='18', date='2014-05-28', duration='190';
INSERT INTO timeReports SET user='Naima', project=8, role='manager', activityType='21', date='2013-02-25', duration='100';
INSERT INTO timeReports SET user='Naima', project=9, role='manager', activityType='23', date='2013-03-03', duration='150';
INSERT INTO timeReports SET user='Naima', project=9, role='manager', activityType='22', date='2013-04-08', duration='160';
INSERT INTO timeReports SET user='Naima', project=10, role='manager', activityType='13', date='2013-04-01', duration='150';